Controllers/EstudianteController.cs
using Microsoft.AspNetCore.Mvc;
using _9APractica2EquipoGandy.Models;
using _9APractica2EquipoGandy.Service;

namespace _9APractica2EquipoGandy.Controllers;

public class EstudianteController : Controller
{
    private readonly ILogger<EstudianteController> _logger;
    private readonly IEstudianteRepository _estudianteRepository;

    public EstudianteController(ILogger<EstudianteController> logger, IEstudianteRepository profesorRepository)
    {
        _logger = logger;
        _estudianteRepository = profesorRepository;
    }

    public async Task<IActionResult> Index()
    {
        var modelo = new EstudianteViewModel();
        modelo.Estudiantes = await _estudianteRepository.Listar();
        return View(modelo);
    }

    [HttpGet]
    public async Task<IActionResult> Eliminar (long id)
    {
        await _estudianteRepository.Eliminar(id);
        return RedirectToAction("Index");
    }
}

Controllers/ProfesoresController.cs
using Microsoft.AspNetCore.Mvc;
using _9APractica2EquipoGandy.Models;
using _9APractica2EquipoGandy.Service;

namespace _9APractica2EquipoGandy.Controllers;

public class ProfesorController : Controller
{
    private readonly ILogger<ProfesorController> _logger;
    private readonly IProfesorRepository _profesorRepository;

    public ProfesorController(ILogger<ProfesorController> logger, IProfesorRepository profesorRepository)
    {
        _logger = logger;
        _profesorRepository = profesorRepository;
    }

    public async Task<IActionResult> Index()
    {
        var modelo = new ProfesorViewModel();
        modelo.Profesores = await _profesorRepository.Listar();
        return View(modelo);
    }

    [HttpGet]
    public async Task<IActionResult> Eliminar (long id)
    {
        await _profesorRepository.Eliminar(id);
        return RedirectToAction("Index");
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _9APractica2EquipoGandy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_9APractica2EquipoGandy.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css">
</head>

<body>
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" asp-area="" asp-controller="Home"
            asp-action="Index">Escuela</a>
    </header>

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-3 d-md-block bg-light sidebar">
                <div class="container-fluid pt-1">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="DivisionAcademica" asp-action="Index">
                                <i class="bi bi-building"></i>&nbsp;
                                Divisiones académicas
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="CarreraProfesional" asp-action="Index">
                                <i class="bi bi-bookmark-star"></i>&nbsp;
                                Carreras profesionales
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Profesor" asp-action="Index">
                                <i class="bi bi-person-rolodex"></i>&nbsp;
                                Profesores
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Estudiante" asp-action="Index">
                                <i class="bi bi-person-rolodex"></i>&nbsp;
                                Estudiantes
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="GrupoEstudiante" asp-action="Index" >
                                <i class="bi bi-people"></i>&nbsp;
                                Grupos
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <main class="col-9 px-md-6">
                @RenderBody()
            </main>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>